version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${APP_ENV}
    container_name: node-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db          
      DATABASE_NAME: app_db     
      DATABASE_USERNAME: app_user  
      DATABASE_PASSWORD: password123 
    depends_on:
      db:  
        condition: service_healthy
    
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: app_db         
      POSTGRES_USER: app_user    
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: